### ISSUE TITLE
Nohboard not starting up. 

### ISSUE THREAD

**Issue by R7Toonz** [ThoNohT/NohBoard#100]
Everytime i try to run the file, it just pops up with the windows protection screen, and when i click run anyway it just says it has stopped working????

**Comment by flyingmongoose** [comment]
So I've personally been having a different issue where i can't load between different keyboards, it just basically says the file path can't be found (I'm on an alternate drive from my OS drive, may be related).

This may or may not necessarily be related to your issue, but ultimately it makes it so the software doesn't work.

The only resolution I've found is to re-extract the latest edition on top of the latest version I've extracted (effectively reinstalling) and starting over and reloading whatever keyboard I'm trying to load. This seems to work 99% of the time for a few issues I've run into.

**Comment by joao7yt** [comment]
Maybe try running it with admin privileges

**Comment by ThoNohT** [comment]
NohBoard isn't digitally signed, so some windows installations or antivirus programs may flag it as malicious, as it also does keyboard and mouse hooking. This is basically a case of letting your computer believe you that NohBoard is allowed to run.

**Comment by terminator0521** [comment]
Try deleting the **NohBoard.json** file. This worked for me.
