### ISSUE TITLE
Style changes wont work

### ISSUE THREAD

**Issue by Jedgji** [ThoNohT/NohBoard#102]
Any style change to any element of a keyboard that I make wont take effect. Furthermore, the keyboard background color resets to green (the default) every time I go back into the style change menu, and the rest of the style changes seem to work, but actually change nothing about the keyboard.

**Comment by ThoNohT** [comment]
Do you save your style after changing it?

**Comment by ThoNohT** [comment]
I checked it out. Styles do seem to save properly. But changing the background color is indeed broken.

**Comment by ThoNohT** [comment]
Fixed in https://github.com/ThoNohT/NohBoard/releases/tag/v1.2.2
