### ISSUE TITLE
Mouse Speed Indicator Style Changes not taking effect

### ISSUE THREAD

**Issue by Davoleo** [ThoNohT/NohBoard#106]
Software Version: `1.2.2`

Video Explaining the bug:
https://streamable.com/1v6bv

**Comment by Kotsuha** [comment]
Encounter this issue today in v1.2.2. Is there any progress about this issue?

**Comment by ThoNohT** [comment]
Should be solved in 2602ef4aa38ea12cfa23c3d9becbab6da57b28f0.

Could anyone test this? https://ci.appveyor.com/project/ThoNohT/nohboard/builds/31936019/artifacts

**Comment by joao7yt** [comment]
Working.
