### ISSUE TITLE
Can't set both OutlineWidth to 2

### ISSUE THREAD

**Issue by JapanYoshi** [ThoNohT/NohBoard#108]
I tried to set OutlineWidth of both idle and pressed keys to 2, but every time I saved it from the GUI, it turned one of them to 1. I had to manually edit default.style in order to change it.

**Comment by ThoNohT** [comment]
I'm unable to reproduce this. I  tried it both in the keyboard style, and in a key's element style. In both cases I was able to successfully edit the outline width of either or both at the same time.

**Comment by ThoNohT** [comment]
Actually managed to reproduce something like this. Probably related. Good news is it'll be fixed in the next commit.

**Comment by ThoNohT** [comment]
Fixed in 4d0ea4d169a5e36bb081dcc3f5429fc13ed90786
