### ISSUE TITLE
Unable to capture the keyboard of DiRT 4

### ISSUE THREAD

**Issue by violetice** [ThoNohT/NohBoard#109]
OS：Windows 10 x64
Version：1.2.2
Game：DiRT 4

Window and full screen cannot capture the keyboard
Not clear is DirectX game, can not confirm

=============================

系统：Windows 10 x64
版本：1.2.2
游戏：尘埃4

窗口和全屏都无法捕获键盘
不清楚是不是 DirectX  游戏，无法确认

**Comment by ThoNohT** [comment]
If the keypresses aren't being detectd, try running it as admin, and starting it before the game. Otherwise, there is nothing I can do about this.
