### ISSUE TITLE
Key 1028(Mouse Movement) moves wiredly when in a game.

### ISSUE THREAD

**Issue by KristopherKram** [ThoNohT/NohBoard#11]
The key 1028(Mouse Movement) moves weirdly when in a game. I've test this in Minecraft and Team Fortress 2. The indicator dot moves wildly left and right when you move the mouse left. Works fine when not in a game though.

**Comment by larsbrix** [comment]
i had this issue on my project. reason is that game engines reset the mouse position every frame.  
a working solutiuon is to check the current position against the screen/window center instead of the previous position

here's a gist of my source https://gist.github.com/larsbrix/bfe1972446134a10eb09

**Comment by ThoNohT** [comment]
Is this still the case?

**Comment by KristopherKram** [comment]
Using version 0.17b from sourceforge the bug still exists. Turing to the left while in Team Fortress 2 for example results in the mouse circle showing movement of the mouse to the right while the mouse was just moved to the left. Desktop applications works fine it just seems to be games that are causing this issue. Assuming that th reason for this is because of @larsbrix comment.

**Comment by ThoNohT** [comment]
@KristopherKram Could you try using v0.2.0 from the GitHub releases? If I'm going to fix it, it will be in the rewrite.

**Comment by KristopherKram** [comment]
The issue still exists using the NohBoard_ReWrite_0.2.0 build. But no where near as bad as it was originally.

**Comment by ThoNohT** [comment]
Thanks for the confirmation. Next time I get around to working on NohBoard I'll try to see if I can implement @larsbrix 's fix.

**Comment by ThoNohT** [comment]
I have made an experimental fix, see 3f84dd4c7ee75802fcadd08757d2abe508bbe024
If anyone can build from source he can test it. Otherwise I will release this in a few days once I have had some time to  get a few other changes in.

**Comment by Matundan1** [comment]
I have this same problem even now in 2020 with ver 1.2.2 How can I fix this problem?
