### ISSUE TITLE
dont work when im in another window

### ISSUE THREAD

**Issue by NISCCDSA** [ThoNohT/NohBoard#113]
When im in clicking in another window the keyboard and the mouse doesnt work please help

**Comment by MeatPony** [comment]
same

**Comment by flyingmongoose** [comment]
Try running nohboard in administrator mode

**Comment by ThoNohT** [comment]
Yep, there is nothing I can do about this. The only option is to try running it as administrator so it gets a higher priority for hooking the keyboard and mouse.
