### ISSUE TITLE
Disable mousehooking (add a checkbox like old NohBoard?)

### ISSUE THREAD

**Issue by klkluer** [ThoNohT/NohBoard#115]
For some reason, some specific games (in this case Quake 3 engine games) doesn't like when something hooks the mouse input, it generates jarring skips and overadjusts any movements you do. Smooth turns are no longer smooth, tiny flicks become big. Personally I don't need or actually want to display my mouse inputs in OBS, just the keyboard. Why this issue happens in the first place might be harder to figure out.

I have removed all elements that have to do with the mouse, but it still happens as if it is hooked.  In the old NohBoard version this doesn't happen as there is a way to make sure NohBoard does not hook the mouse via a simple checkbox, it would be really cool if that could be added to this, or atleast some way via configuration files to disable it. Perhaps if there are no mouse-related elements present in the layout, mousehooking should be disabled automatically?

To clarify; this does happen with the old NohBoard also, as soon as you hook the mouse. Simply unhooking the mouse stops via the checkbox stops it. 

To counter-act the effect, it is possible to use "rinput" to hook into the .exe that have these problems.

**Comment by ThoNohT** [comment]
I have now implemented that mouse hooking is only enabled if there are mouse related elements on the screen. Keyboard hooking is also done if there are keyboard elements on the screen.
This is done in e119c28c2ab67d17e7914abe3e3fd084ec01748e.

Would someone test this? https://ci.appveyor.com/project/ThoNohT/nohboard/builds/31952462/artifacts

**Comment by joao7yt** [comment]
can't open nohboard. log attached.
[20200404-120428.73229831.log](https://github.com/ThoNohT/NohBoard/files/4431756/20200404-120428.73229831.log)

the previous version runs fine, this last one doesn't

**Comment by ThoNohT** [comment]
Am I glad I asked for testing. I think this should fix it: 9cbcf3f83142542c2b4c9fa9141c3fb004d67a47

Can be tested here: https://ci.appveyor.com/project/ThoNohT/nohboard/builds/31952724/artifacts

**Comment by joao7yt** [comment]
Then I think only klkluer can test this with quake 3

**Comment by ThoNohT** [comment]
As long as no other strange side effects have occurred then that's all the testing you can do indeed.

@klkluer Could you test this?

If it takes too long before I get a response, I will assume it works, create the release and close this issue. But you can always reopen it if you find out something is wrong with it. For now I will focus on some other issues.

**Comment by ThoNohT** [comment]
I released v1.3.0, and will close it for now. As I said before @klkluer pleae reopen if you still have the issue.
