### ISSUE TITLE
Outlines overlapping

### ISSUE THREAD

**Issue by joao7yt** [ThoNohT/NohBoard#116]
If the Loose Outline width is greater than the pressed one, you can see the Loose Outline under the pressed one when pressing the key.

**Comment by ThoNohT** [comment]
There's not much I can do about that. For performance reasons, all loose keys are rendered onto the background in one go. And all pressed keys are individually rendered over that. So this effect will always be present. This is the same reason why transparent pressed keys are not an option.

**Comment by joao7yt** [comment]
You could display a message at the bottom of the window is red in case the user chooses the pressed outline smaller than the loose one. Or something like that... Or simply don't let the user do this

**Comment by ThoNohT** [comment]
Hmm, but what if they want it as a desired effect?

**Comment by joao7yt** [comment]
Then just display the warning text at the botton of the Style window I guess

**Comment by ThoNohT** [comment]
Alright, I think that's a reasonable solution.

**Comment by ThoNohT** [comment]
Added in bc4e57e0911752031727f2d1e99b6af605d23180.

Could you check it out: https://ci.appveyor.com/project/ThoNohT/nohboard/builds/31954602

(AppVeyor won't load for me at the moment)

**Comment by joao7yt** [comment]
nice detail. it's working
