### ISSUE TITLE
Weird Black Edges

### ISSUE THREAD

**Issue by Arfha01** [ThoNohT/NohBoard#118]
### So I open Nohboard and It looks normal, when I put it on obs studio, Its show Weird black edges  on it right and bottom sides ### 

![obs64_nsotWuCLt4](https://user-images.githubusercontent.com/59753854/79399874-136ee980-7fb7-11ea-8912-0cdf9a1f9a46.png)

**Comment by joao7yt** [comment]
That's weird, I couldn't reproduce it here. Can you record a video of your screen showing you adding the window capture? Maybe also show the NohBoard window too...

**Comment by Arfha01** [comment]
ok

**Comment by Arfha01** [comment]
Here the Video

https://www.youtube.com/watch?v=c_3bSEoOsRk

**Comment by ThoNohT** [comment]
Perhaps some scaling issues with Windows? Try at 100% scale of it is not set to that.

**Comment by Arfha01** [comment]
Ok, thank you for fixing this problem

**Comment by joao7yt** [comment]
hahaha you drawing on it hahaha
