### ISSUE TITLE
High DPI Support (Screen DPI)

### ISSUE THREAD

**Issue by TakaSoap** [ThoNohT/NohBoard#119]
This documentation may be helpful.
https://docs.microsoft.com/en-us/dotnet/framework/winforms/high-dpi-support-in-windows-forms

**Comment by joao7yt** [comment]
What would this practically mean for NohBoard?

**Comment by TakaSoap** [comment]
> What would this practically mean for NohBoard?

I am currently using a 4K screen and my scaling setting is 250% now. The text would be blurred if there is no high DPI support.
![image](https://user-images.githubusercontent.com/34995160/79471949-d4cc4400-8035-11ea-96b7-0bf0c6624d21.png)
There is an obvious difference between the title and the right-click menu.

**Comment by joao7yt** [comment]
OOOOOH, now I see... I was thinking about mouse sensor's DPI hahaha That makes sense tho, would be a nice feature.

**Comment by TakaSoap** [comment]
> OOOOOH, now I see... I was thinking about mouse sensor's DPI hahaha That makes sense tho, would be a nice feature.

My fault. I didn't make it clear LOL

**Comment by ThoNohT** [comment]
@TakaSoap Could you try what effect the .net-core version has on DPI awareness?

Try the build from here: https://ci.appveyor.com/project/ThoNohT/nohboard/builds/32761538/artifacts (If the small download doesn't work, either install the[ .net-core runtime](https://dotnet.microsoft.com/download/dotnet-core/current/runtime), or run the self contained version, that should work anyway (is just a big download).

**Comment by TakaSoap** [comment]
> @TakaSoap Could you try what effect the .net-core version has on DPI awareness?
> 
> Try the build from here: https://ci.appveyor.com/project/ThoNohT/nohboard/builds/32761538/artifacts (If the small download doesn't work, either install the[ .net-core runtime](https://dotnet.microsoft.com/download/dotnet-core/current/runtime), or run the self contained version, that should work anyway (is just a big download).

![image](https://user-images.githubusercontent.com/34995160/81558281-fd8af380-93bf-11ea-8c00-ec4b94a91650.png)
![image](https://user-images.githubusercontent.com/34995160/81558356-1f847600-93c0-11ea-9867-5303a0af935b.png)
Seems that it is still blurred in high DPI...

**Comment by TakaSoap** [comment]
![image](https://user-images.githubusercontent.com/34995160/81560253-9d964c00-93c3-11ea-81e6-bb6a503da41a.png)
Changing the high DPI scaling override setting works, but the window will become too small.
If it is performed by "System" or "System (Enhanced)", the will would not appear at all.

**Comment by ThoNohT** [comment]
Hopefully, this version has proper high DPI support: https://ci.appveyor.com/project/ThoNohT/nohboard/builds/32800646/artifacts. Could you test agin @TakaSoap ?

**Comment by TakaSoap** [comment]
> Hopefully, this version has proper high DPI support: https://ci.appveyor.com/project/ThoNohT/nohboard/builds/32800646/artifacts. Could you test agin @TakaSoap ?

![image](https://user-images.githubusercontent.com/34995160/81677517-9a629500-9483-11ea-8450-950762ce09c6.png)

It works pretty well!! But the letters on the keyboard are too big, a small problem though.

**Comment by ThoNohT** [comment]
https://ci.appveyor.com/project/ThoNohT/nohboard/builds/32825552/artifacts

Next version, all font sizes compensated for the DPI settings. Testing time again, @TakaSoap .

**Comment by TakaSoap** [comment]
> https://ci.appveyor.com/project/ThoNohT/nohboard/builds/32825552/artifacts
> 
> Next version, all font sizes compensated for the DPI settings. Testing time again, @TakaSoap .

![image](https://user-images.githubusercontent.com/34995160/81725037-da436f80-94b7-11ea-9742-080639438689.png)

Perfect. Now I have noticed that the fonts of pressed keys are clear and sharp, but those are not pressed won't.

**Comment by ThoNohT** [comment]
That's now fixed in https://ci.appveyor.com/project/ThoNohT/nohboard/builds/32826423/artifacts

I do notice that  this introduced some artefacts in some of the keyboards:
![afbeelding](https://user-images.githubusercontent.com/3800650/81728495-d64d2880-948a-11ea-8d9f-d1d992154abb.png)

I'm not really sure what can be done about that. It might be best if I allow a user to toggle the scaled rendering.

**Comment by TakaSoap** [comment]
![image](https://user-images.githubusercontent.com/34995160/81728952-cd297f00-94bd-11ea-9203-329cf435b4c5.png)
![image](https://user-images.githubusercontent.com/34995160/81728990-ddd9f500-94bd-11ea-8af0-652b8172c5ff.png)
Yep, some keyboards with custom keycaps also have scaling problems.
Anyway, really appreciate your work.

**Comment by ThoNohT** [comment]
Hmm, I think that's something I may be able to fix. I'll look into it.

**Comment by joao7yt** [comment]
So, it was meant for using my custom font... Try installing the custom font and see if the font fits inside the squares. it should fit perfectly

**Comment by ThoNohT** [comment]
Yeah, I see now. And I found a but with opening font links and restarting the application while I was testing that.

But then I'll consider this feature implemented. I'll be including it in a release in the future. But for now I want to do some more working on it and testing to see if there aren't any other hidden bugs in since the switch to .net core.

If you want to already use it, you can use the developer build from here: https://ci.appveyor.com/project/ThoNohT/nohboard/builds/32857831/artifacts

**Comment by joao7yt** [comment]
Just to warn you: the .exe from this last build has no icon
