### ISSUE TITLE
NohBoard will not save custom styles

### ISSUE THREAD

**Issue by ChristopherVH** [ThoNohT/NohBoard#120]
Happens after attempting to add images to normal input, the changes may be linked to some image folder that is not being processed correctly. I have hit save as several times but every time I go to close the window the application warns me that I have unsaved changes, After exiting the mapped images do not load correctly.

**Comment by ThoNohT** [comment]
I'll see if I can have a look at this this weekend.

**Comment by ThoNohT** [comment]
Could you upload the keyboard/style you're trying to edit and the image you're setting? So I can  try to replicate it?

**Comment by ThoNohT** [comment]
I have been trying this, and for me it is having no issues saving the styles. So I will really need your example and an explanation on how to reproduce it I fear.

**Comment by itsImDevil** [comment]
I am actually having issues saving custom overlays as well. Every time i save it actually reverts it back to the normal size along with having all the keys I deleted BACK in but as greyed out squares

EDIT: I found the issues.. i was using an older version. Newest version works well!

**Comment by wwbrandon** [comment]
Hey, I'm having the same problem yet I believe I am using the most current version.

I will edit and save a keyboard but it always reverts to the original.
