### ISSUE TITLE
Ctrl selected when alt gr is pressed

### ISSUE THREAD

**Issue by gorru** [ThoNohT/NohBoard#122]
Hi.
I'm customizing a normal keyboard json in order to support italian keyboard layout.
I started duplicating the uk json and changing were requested.
I noticed that when I press the Alt GR key both that key and Ctrl key are selected.
The behaviour is right if I prest the ctrl key.
The bug seems to be present also in the uk layout.
Could you verify?
Thanks in advance
[keyboard.zip](https://github.com/ThoNohT/NohBoard/files/4547458/keyboard.zip)

**Comment by joao7yt** [comment]
What Alt Gr or Alt Graph does is a physical shortcut for pressing Ctrl + Alt... The behavior is right.

**Comment by gorru** [comment]
Should then also the alt key selected?
Why only the ctrl key?
Anyway I think that this behaviour is misleading if I want to show only the
key pressed.
Is there any workaround to achieve this?
Thanks

**Comment by joao7yt** [comment]
The Alt Gr key is in reality a Right Alt, but physically your keyboard also presses the Left Ctrl for you. That's why the Alt Gr (or should I say Right Alt) gets pressed and also the Left Ctrl.

**Comment by gorru** [comment]
Ok. Thanks.

Il mar 28 apr 2020, 20:09 João Mambelli <notifications@github.com> ha
scritto:

**Comment by ThoNohT** [comment]
I can't help this behaviour. I have discussed it before somewhere, but don't remember where. But when a user presses Alt Gr, I get the messages for Ctrl + Alt. If I were to interpret those as Alt Gr, then a user pressing Ctrl + Alt would result in Alt Gr lighting up, which is also not acceptable. So this is a limitation of the hooking mechanism that we will have to live with sadly.
