### ISSUE TITLE
Visual Input Log - (Feature Request)

### ISSUE THREAD

**Issue by dchitra** [ThoNohT/NohBoard#124]
Referencing this [tweet ](https://twitter.com/Artosis/status/1256409590389895169?s=20 )by Artosis (Starcraft 2 Caster/ Starcraft 1 Player) 

I think think this project would be a great candidate to create something like this.  While we can see overlays, having a visual log of the actions similar to fighting game training modes would be really cool (see [here ](https://youtu.be/aJbB38Mrbr8?t=109) for an example of this in Street Fighter training mode)

I'm not sure if NohBoard can do something like this as a layout, or if there'd have to be a separate overlay or effect created for this.  

(Imagine a game of DDR except the moving arrows represent keys you pressed instead of keys you are supposed to press)

**Comment by ThoNohT** [comment]
Similar feature to #111. I may want to make this eventually, since it's being requested a lot, but I don't have time right now. Anyway, track that issue for any updates on it.

**Comment by dchitra** [comment]
cool ty!
