### ISSUE TITLE
Show only keys pressed

### ISSUE THREAD

**Issue by android272** [ThoNohT/NohBoard#128]
I am looking for a way to show only the keys that I press in OBS. I would like a layout that replaces a key or many the letters, numbers, symbols,  and special keys that I type instead of showing the full keyboard or a special layout specifically for games or whatnot. 

Here is a gif of what I am talking about.
![key-mon)](https://i.stack.imgur.com/Kl5xE.gif)

Here is a video on how keymon works.
https://www.youtube.com/watch?v=h5sEcupUJqI

**Comment by ThoNohT** [comment]
If you only want one key, it should be possible by placing all keys on top of each other. Anything that is pressed will be rendered over anything that is unpressed. So if you style all keys such that they show nothing when unpressed, then it will just look like one empty key that is filled whenever you press something. The other keys to the left can be done how NohBoard does it normally.

I saw that there is a history function in keymon. That's not possible in this way. I do plan to eventually create a key history function, but that will be in the style as described in this issue: #111

**Comment by android272** [comment]
Oh I did not know that you could edit the keyboards. That sounds great I
will try that out.

**Comment by midnightfreddie** [comment]
> I will try that out.

Please share if you get it working. What you pictured is pretty much exactly what I want.

**Comment by android272** [comment]
@ThoNohT is there a way to increase the font size? I am almost done with my keyboard but the font is a bit too small. 

Here is a screenshot of my keyboard so far.

![image](https://user-images.githubusercontent.com/5912527/88024324-803ad800-cb00-11ea-81fa-93c1ffb24242.png)

**Comment by ThoNohT** [comment]
Have you checked the keyboard style window:
![image](https://user-images.githubusercontent.com/3800650/88031222-92d30280-cb3c-11ea-9bac-7b99c52c62bd.png)
Double click the pick a font text in order to select the font (and size) for all keys. You can also do the same for individual buttons by opening the element style windows.

I see that this may be a bit unclear, I'll have to look into making the font chooser clearer, or at least improving the documentation.

**Comment by android272** [comment]
Oh, I thought that was referring to the link text box. I suggest changing that to a button. Thanks for the help. I am done with the keyboard. I can fork the project and do a merge request if you like.

**Comment by ThoNohT** [comment]
Sure.  All PRs with new keyboards are welcome.

**Comment by android272** [comment]
Sorry it took so long to get a pull request in but there you go. @midnightfreddie you can download my keyboard [Here](https://github.com/android272/NohBoard/tree/TutorialBoard)

![image](https://user-images.githubusercontent.com/5912527/104968691-8bd66100-59b4-11eb-97ec-4ab3b01ac5b0.png)
