### ISSUE TITLE
Doesn't Work When Minimized (For Streaming)

### ISSUE THREAD

**Issue by rosenq** [ThoNohT/NohBoard#131]
When the window is on screen there is no problem seeing the keys activate when keyboard button is pressed. When the window is minimized (for window capture Streaming) the keys no longer activate.

**Comment by joao-mambelli** [comment]
It’s working properly... you can’t minimize it as it’s capturing the window itself...

**Comment by rosenq** [comment]
Okay, sorry for the false bug report. Any suggestions on how to overcome my
scenario?

**Comment by joao-mambelli** [comment]
You need to keep it maximized, I don't see a problem with it. you will be streaming the game in full screen I guess, nohboard would be running on the background

**Comment by rosenq** [comment]
In my particular case I am streaming full desktop monitor  3440x1440p to a
1920x1080 stream. So the monitor takes up the top 6/7th of the stream and I
have a bottom section for cam, overlay, etc. I'll continue to hunt for a
solution but I need a clean desktop for the stream. I use multiple apps -
MS SQL server, PDFs and webpage. I can see about purchasing a second
monitor.

Thanks for your quick responses.

**Comment by joao-mambelli** [comment]
If NohBoard is behind of another window, it would work fine... put it behind the game for example

**Comment by ThoNohT** [comment]
Yes, nothing I can do about Windows not rendering minimized windows.
