### ISSUE TITLE
disable shift

### ISSUE THREAD

**Issue by varonityy** [ThoNohT/NohBoard#135]
Ive been looking through all the settings and all files, I remember there being a "Disable Shift" options on older versions of NohBoard, is there a way of disable shift now? Is it some sort of boolean that I overlooked within the .kb files?

**Comment by varonityy** [comment]
I found a work around, e.g. "key 49 53 100 43 43 1 ! 0 0" Ill just remove the ! with a 1,  idk why I didnt think of that earlier :D

**Comment by ThoNohT** [comment]
Manually editing all keyboard files was not the way this is supposed to be done. Please check the settings window, and the follow shift / caps lock settings.
