### ISSUE TITLE
Program crashes when I try opening the .exe file

### ISSUE THREAD

**Issue by KaspaTM** [ThoNohT/NohBoard#142]
It says the the program has crashed and says "Could not load file assembly NohBoard.Hooking" want to use the program but every single version has the same error.

**Comment by ThoNohT** [comment]
You probably have an Antivirus running that blocks NohBoard.Hooking.dll, since it sort of acts like a keylogger (it detects all keys you press).

**Comment by KaspaTM** [comment]
How would I disable it then? (Sorry I am a tad bit dumb regarding computers and software especially)

**Comment by ThoNohT** [comment]
I'm sorry, I can't help you with that, it is not related to NohBoard. If you don't know how your antivirus works then I suggest finding someone in your neighbourhood who can help you with it.
