### ISSUE TITLE
Don't know how to disable shift

### ISSUE THREAD

**Issue by O2Switch** [ThoNohT/NohBoard#145]
I've been setting up nohboard since this morning and managed to get the exact setup I want. However, I don't want to have the keys change whenever I press shift or caps lock. I tried checking settings, but I don't see an option that refers to disabling shift or changing to caps. Any help is appreciated. :)

**Comment by ThoNohT** [comment]
![afbeelding](https://user-images.githubusercontent.com/3800650/105194763-375cee00-5b3a-11eb-8a53-3d5dc0507581.png)
This should cover all your needs?

**Comment by O2Switch** [comment]
Where can I find that page? When I open nohboard > right click > settings > I don't see it there.

**Comment by O2Switch** [comment]
I'm on version 0.17b if that changes anything

**Comment by O2Switch** [comment]
Ah wait, I realized how stupid I am. Thank you so much for the quick reply! I truly appreciate it.
