### ISSUE TITLE
Buttons not picking up keypresses

### ISSUE THREAD

**Issue by TheEthanExpress** [ThoNohT/NohBoard#146]
I'm trying to set up the program and I changed it so that some of the keys will detect multiple keys when pressed, and for some reason, the program just stopped picking up the keypresses and it won't fix itself even if I restart the program or reload it. not sure why its happening. it did work initially though but I'm not sure what caused it to stop working
![image](https://user-images.githubusercontent.com/29741411/106839086-1aa8d600-6663-11eb-8b33-fde8a4877d4f.png)

**Comment by ThoNohT** [comment]
When you add multiple keycodes, all of them need to be pressed for them to light up. If you want one key to respond to multiple keys individually, just make multiple key definitions and place them on top of eachother.
