### ISSUE TITLE
Feature request: Save last keyboard settings

### ISSUE THREAD

**Issue by Avasam** [ThoNohT/NohBoard#148]
It would be a very nice quality of life improvement if the last keyboard settings (Category, Definition and Style) were saved so that they're selected automatically when opening the app.

**Comment by ThoNohT** [comment]
It does this. If it isn't saving the settings for  you, perhaps you have it running in a place where it doesn't have permission to write away its settings file?

**Comment by Avasam** [comment]
My bad, that seems like an obvious thing to check for in hindsight. I've updated permissions and made sure the folder wasn't readonly, it works now. Anyway, thanks for the quick response and the cool program.
