### ISSUE TITLE
Transparent Background

### ISSUE THREAD

**Issue by mnoreke** [ThoNohT/NohBoard#150]
When using the keyboard capture window to record in OBS, it would be nice to have a transparent background so that just they keys are visible.

Is this possible to do today, or an easy update?

**Comment by joao-mambelli** [comment]
not possible, only if it was a implemented feature in obs. in this case you just need to add a key color filter in your capture to remove the solid color background of nohboard

**Comment by ThoNohT** [comment]
Indeed, use chroma/color key to do this.
