### ISSUE TITLE
Can't edit settings

### ISSUE THREAD

**Issue by Animyos** [ThoNohT/NohBoard#155]
Hello, wanted to edit settings in NohBoard, but after restart, nothing changed. Further explanation in this video: [https://youtu.be/fLXLe2Ugb8U](https://youtu.be/fLXLe2Ugb8U)

**Comment by Gubblminator** [comment]
I see you use v0.17b which is really outdated? Try and use the latest version

**Comment by Animyos** [comment]
Ok. I've discovered it in the OBS Forum and donloaded it with a Github Link shown there. I'll update my version now.

**Comment by Animyos** [comment]
OK, thanks. Now I can load Keyoard layouts, everything woks. Thank you!
