### ISSUE TITLE
Add controller support

### ISSUE THREAD

**Issue by Thedoczek** [ThoNohT/NohBoard#158]

**Comment by ThoNohT** [comment]
Related to #117

**Comment by EmanueleCiriachi** [comment]
Hi, sorry for replying this late, I had missed the notification.

I updated the release, the crash was caused by failing to update the baseline configuration. Would you mind to try again?

**Comment by Thedoczek** [comment]
> Hi, sorry for replying this late, I had missed the notification.
> 
> I updated the release, the crash was caused by failing to update the baseline configuration. Would you mind to try again?

Umm... Wrong issue? This comment seems completely unrelated
