### ISSUE TITLE
Nohboard window problem

### ISSUE THREAD

**Issue by deific-jam** [ThoNohT/NohBoard#161]
There is an extra space displayed on the obs when I add Nohboard, and when I hover my cursor over the Nohboard window, the cursor start creating a trail.

https://user-images.githubusercontent.com/69472336/121769302-6f63dc80-cb80-11eb-99d2-26b0ca3df8c0.mp4

Please someboady help me.

**Comment by ThoNohT** [comment]
Related to #147
