### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by KVRR07** [ThoNohT/NohBoard#163]
Hey, I was making a keyboard in Nohboard but when I put in a link for a font (from dafont), the font didn't work and just stayed the same as Courier New. Am I using the Font feature wrong (like putting a wrong link in) or is it just a bug from Nohboard? Thanks!

**Comment by ThoNohT** [comment]
Check how fonts are used for example in this file: https://github.com/ThoNohT/NohBoard/blob/master/keyboards/joao7yt/fps/clean-black_clean-white.style#L16

You don't specify the link to the font such that NohBoard uses it. You specify the name of a font (family) that should be installed in the `FontFamily` field, and if so it will automatically be used. But if that font is not installed on the user's computer, NohBoard can show the link to the font, which you specify in the `DownloadUrl` field. It is then up to the user to either download and install the font, and then restart NohBoard to use the keyboard with the font, or just fall back to an installed font.
