### ISSUE TITLE
Failed to load settings

### ISSUE THREAD

**Issue by Gm1u** [ThoNohT/NohBoard#166]
Whenever I try opening up nohboard normally instead of opening as admin it says: Failed to load the settings: Access to the path
"C:\WINDOWS\system32\Nohboard.json" Is denied.
I've tried looking for the nohboard.json file in system 32 but it isn't there, does anybody know how to fix this?
And every-time I open the settings, change something, and then close the settings it would close nohboard.

**Comment by ThoNohT** [comment]
It will try to load the settings from the path where NohBoard.exe is located. If you placed it in C:\WINDOWS\system32\, then that's where it will try to load the settings from, but your regular user account has no access to it.

To solve this, place NohBoard in a more sensible place.

**Comment by Gm1u** [comment]
So If I place it in "D" Drive it should work right?
