### ISSUE TITLE
Adding Images to keys is either not working or not intuative.

### ISSUE THREAD

**Issue by sorryvol** [ThoNohT/NohBoard#169]
Doing into the element styles there a section that says "Image" with a text box beneath it. I'm not sure if I'm doing it wrong but I enter the name of the image, and put the image itself in the same directory as the NohBoard.exe and also in the keyboard save directly just to be sure. The key didn't change at all so I tried putting the directory of the image in the text box, which also didn't work. when I went to edit the directory again all the slashed had been removed from the string so I'm pretty sure that isn't how to do it.

I'm just not quite sure how I should be adding images to the keys.

**Comment by ThoNohT** [comment]
Please read https://github.com/ThoNohT/NohBoard/wiki/How-To-Use#folder-structure-

**Comment by Djablo4wow** [comment]
![image](https://user-images.githubusercontent.com/91888118/210104702-53a62ec0-a602-4d8c-9bba-0dfdb0b91815.png)
![image](https://user-images.githubusercontent.com/91888118/210104719-c453fa26-e469-4294-98f4-1fbe5f949269.png)
![image](https://user-images.githubusercontent.com/91888118/210104860-7dc12111-b4a0-4782-b1d1-e515e7adcd51.png)
![image](https://user-images.githubusercontent.com/91888118/210104732-c1e5d031-27c8-472f-97c8-fe56b06d31d2.png)
![image](https://user-images.githubusercontent.com/91888118/210104776-9a60950b-0f0f-4c79-8024-5122f79ed4e9.png)

Doesn't work, I don't understand either?

**Comment by Joost-L** [comment]
^For me it only changed after I modified the background color
