### ISSUE TITLE
Suggestion: Add an option for PNG overlays

### ISSUE THREAD

**Issue by Mitsunee** [ThoNohT/NohBoard#17]
It might be neat, if there was an option that enables the use of PNG overlays.

The syntax of the key layout files would then be:
key keyCode x y width height NormalText ShiftText ChangeOnCaps SmallFont Overlay[0/1] OverlayWhenUnpressed[0/1] OverlayPath [relative/"absolute" path]

**Comment by ThoNohT** [comment]
Implemented in the rewrite
