### ISSUE TITLE
Inputs lasting too long

### ISSUE THREAD

**Issue by GGelatin** [ThoNohT/NohBoard#180]
I have set "Show keypresses for at least:" to 0ms but the display holds inputs for a few frames regardless.
In a 60FPS fighting game, my single frame button presses (~16.667ms) are extended to a minimum of three frames (~50ms).

**Comment by ThoNohT** [comment]
NohBoard runs at 33 fps. So it will show presses for 33 ms. You can change this by changing the UpdateInterval to something lower like 16 for example, in NohBoard.json
