### ISSUE TITLE
Releases after 1.2.1 has a malware, please fix

### ISSUE THREAD

**Issue by skywalk1411** [ThoNohT/NohBoard#184]
Please don't just disregard this issue, it was fine before, something (lots I should say) changed since 1.2.2, I would enjoy a 1.3.0 without the "false positive" 

1.3.0 https://www.virustotal.com/gui/file/d868ada36466e3f88d3edb023d333fac503fa48f282c27dae6148d044a65b59d infected
1.2.2 https://www.virustotal.com/gui/file/b20084d1bcd9e446612593a6738f12bbfbc5256abdff1f36b60138c0b8f29ac0 infected
1.2.1 https://www.virustotal.com/gui/file/451ff3dbc5d03ae2010d49a31cdaef2c833e2e006027c33383023ae5957eaaea clean
1.2.0 https://www.virustotal.com/gui/file/797a874c05cff3d8799e10c0981c110b3cd9bfb3aa0a1dd89d3e3affea109a83 clean
1.0.1 https://www.virustotal.com/gui/file/e3d4d00aba43ce95c6b10177f8afcef9b847e9c94fc245ce2c66f650f665cda2 clean

**Comment by ThoNohT** [comment]
https://github.com/ThoNohT/NohBoard/commit/feddfcf4879ecbe4df9e4437224d7d7927aa2682

This is the only code change between 1.2.1 and 1.2.2.  I wouldn't call that lots. Do note that NohBoard is basically a keylogger, which may cause some applications to flag it.

**Comment by skywalk1411** [comment]
🤷 what can I say, I will stick to 1.2.1.

Thanks for the hard work.

**Comment by ThoNohT** [comment]
I'll run a manual build through that scanner when I have some time to see what comes up. The CI tool is the only thing that might have influenced it.
Though I highly suspect it is something detecting the keyboard and mouse hooks in NohBoard, it never hurts to verify.

**Comment by ghost** [comment]
> Releases after 1.2.1 has a malware

It is **NOT** a virus.

It **ONLY** happens with MaxSecure, which I don't think many people use, and it also happens with MANY safe programs.

It is most definitely a false positive.
