### ISSUE TITLE
The key code changes to 1. BUG

### ISSUE THREAD

**Issue by TailsGamer2020** [ThoNohT/NohBoard#185]
When I try to change the key code it changes itself to 1. here some pics
![BugPic1](https://user-images.githubusercontent.com/69054260/166091119-62d72210-e5d2-4fdd-9353-209f82f51775.png)
![BugPic2](https://user-images.githubusercontent.com/69054260/166091123-e641a371-7144-4846-9ba1-9ffa176f5d18.png)
![BugPic3](https://user-images.githubusercontent.com/69054260/166091127-c3313c2f-babd-4926-9d22-c6c3c6c9618d.png)
![BugPic4](https://user-images.githubusercontent.com/69054260/166091132-0bdee2b4-b31f-4af6-a7b6-56767ab901dd.png)
help

**Comment by ThoNohT** [comment]
The 1 on top is only the input. If you want to add a new keycode it should react to, you need to either type it in there or detect it, and then click Add.
Note that all the keycodes in the list need to be pressed in order for a key to light up.
