### ISSUE TITLE
Not Show Any Button Of Keyboard 

### ISSUE THREAD

**Issue by shirokuma-desu** [ThoNohT/NohBoard#192]
![image](https://user-images.githubusercontent.com/77010056/206892352-546077b7-38c8-444e-837a-1d99c757e6fd.png)

**Comment by Warpzone4** [comment]
Same problem I'm having, currently using Windows 11 if that matters at all

**Comment by Warpzone4** [comment]
LMAO RIGHT CLICK ON IT
it works fine you gotta select a keyboard to load
