### ISSUE TITLE
Make font and font size customizable

### ISSUE THREAD

**Issue by ThoNohT** [ThoNohT/NohBoard#2]
This should probably be a property of a keyboard layout file.

**Comment by vallamost** [comment]
Where is the global font setting located at? I don't see it in the Settings menu; asking for the answer as others may find this in the top google result for this question.

**Comment by Raven-Singularity** [comment]
> Where is the global font setting located at? I don't see it in the Settings menu; asking for the answer as others may find this in the top google result for this question.

Yup, this is the top web result for me, looking for how to change NohBoard font size.  Haven't figured out how to change it yet.

Edit: So I figured it out.

**To anyone else wanting to change the NohBoard font size:**

1. Go to your NohBoard program directory
2. Go to the folder `\keyboards\global\`
3. Load the `.style` file(s) being used by your keyboard(s) into a text editor (i.e. Notepad)
4. Find the two font settings in the `.style` file (one for when a key is unpressed/inactive, the other for when it pressed/active)

They look like this:
```
        "FontFamily": "DejaVu Sans",
        "Size": 18,
        "Style": 1
```

**FontFamily:**
The name an installed font on your system.  You can get the font name by opening up the font `.ttf` file (probably located in `C:\Windows\Fonts`) in Windows Explorer.

**Style:**
Style is made up of 0=Regular, 1=Bold, 2=Italic, 4=Underline, 8=Strikeout.  I assume you can add them up, so Bold+Italics would be 3.

**Size:**
The size of the font, I think measured in points, as it seems to scale with Windows font scaling.

Note: I needed to disable Windows font scaling to prevent issues with my NohBoard.
I was using a large text scale in Windows (300% on my 4K screen), which made my taller NohBoard keyboards go off the bottom of the screen and break OBS window capture.

If you want to disable Windows font scaling for your NohBoard:
1. Right-click on the NohBoard executable, and select `Properties`
2. Go to the `Compatibility` tab
3. Click on `Change high DPI settings`
4. Enable the checkbox for `[x] Override high DPI scaling behaviour`
5. Change the `Scaling performed by` drop-down to `Application`
6. Click Apply/Okay

Hopefully this helps the next person looking to change NohBoard font sizes!
