### ISSUE TITLE
Handling custom fonts

### ISSUE THREAD

**Issue by ThoNohT** [ThoNohT/NohBoard#23]
I do not want to ship custom fonts with NohBoards, but as users wish to create styles that use... custom fonts, it might be nice to make a feature where a style can specify which font to download, and having NohBoard link it for the user to install. If the font is not installed, some default font should be specified to fall back onto.

**Comment by joao7yt** [comment]
I downloaded your code but I think I can't help with it since I'm new at it... 

I was thinking of in the keyboard style having a text box where you could list links to download the fonts, then it would auto download it if a checkbox saying something like "Auto download custom fonts" was checked. But it seems a bit odd... Why instead of doing it, you just don't load a default font if the used one is not found and warn the user about it? Instead of crashing the program? I think it would be simplier.

And also, the dafont.com, a huge website for free fonts, don't provide the true link with the .tff file, which would make hard to download using C#.

To avoid the default font also not existing in the user system, you could also have the default font compiled inside your .exe.

**Comment by joao7yt** [comment]
In the case that you warn the user: if the style is an official one (then you would have to create a list in your code listing the styles/definitions that are released with the download of nohboard), you can tell in the warn that the link to download the font is in the README. If the style is not an official one, you can tell to the user to get in touch to the style creator to get the required font. 

The warn would also have an option to not show it again.

Note that when loading a deafault font, it wouldn't change the styles, the style would keep the custom font, you would just change it to show the keyboard. in other words, if the user close and open the program, the message would show again...

**Comment by joao7yt** [comment]
Or show a clickable link in the warn, leading the user to the download. Then the button/checkbox to disable the messages would call something like "Don't show these messages again."

**Comment by joao7yt** [comment]
Have you heard of [Google Fonts](https://developers.google.com/fonts/)? Could this feature be implemented using it?

**Comment by joao7yt** [comment]
[This seems to be interesting](https://developers.google.com/fonts/docs/developer_api#a_quick_example). Then NohBoard just need to download the wanted font file from the "files" section and load it using [PrivateFontCollection](https://docs.microsoft.com/pt-br/dotnet/api/system.drawing.text.privatefontcollection?redirectedfrom=MSDN&view=netframework-4.7.2).

**Comment by joao7yt** [comment]
But how will the user get the actual font if you don't want to ship custom fonts with NohBoard? I was thinking the user would download a keyboard style which would have a link somewhere the .json which would auto download the font for the user as soon as the user loaded the style.

**Comment by ThoNohT** [comment]
That's a possibility yes. But still that doesn't require the API. If you include simply a direct link, anywhere then all I need to do is download the file at that link.

**Comment by joao7yt** [comment]
Then it would be the creator responsibility to host the file somewhere, right? And if the font comes from a website that compresses in a .zip or .rar it's fonts?

**Comment by ThoNohT** [comment]
I feel like it would for now be fine to just prompt the user to visit a website which hosts the font. Then have them download and install it. Once it's installed, NohBoard can then use the font without having to fall back on another font.

**Comment by joao7yt** [comment]
Would the website link be stored in the .json or the .style?

I think it would be cool if this prompt had the full link in the text, so the user can see the site before clicking it and 2 buttons: "Reload style" and "Use default font".

If the user chooses the first one, the program will try to load it again.

If the user chooses the second option, the program would simply check whether the font being loaded exists or not, if not, it would then load the default font instead. Would avoid the user being prevented from using the style if he/she doesn't want to deal downloading custom fonts. What do you think?

**Comment by ThoNohT** [comment]
1.  The fonts would be stored in the .style file. More specifically, they would be stored within the "Font" element of each key that has a downloadable font family. If there is no download link, the link can just be omitted.
  - This means that you could place different links for multiple instances of the same FontFamily. The result is probably going to be that NohBoard only shows the first one. This means that it's actually also okay to only include the link in one of the entries where the custom font is used.

  - In the majority of the cases, the default element style will have the font, so this is not really an issue anyway then.

2. Yes, I definitely want to show the full link for each font the user can be downloading. I don't want hidden links to malicious websites to be a thing.

  - Ideally, I'd even blacklist certain sites like tinyurl, to prevent people from hiding the url and/or making money out of font downloads.

3. The reload thing sounds nice.

4. And yes, I'm actually not sure about even providing an alternative font, because that might not be installed either. So perhaps just fall back to an actual default system font like Arial or so.

5. Could you supply me with your style with the custom font? I seem to have misplaced it.

**Comment by joao7yt** [comment]
Yes yes, I meant a system default font...

Here's it: https://mega.nz/#!OclCCQwT!Mk6TWMZmA7d_Aw99pRbJpFVtNUk3_EDcpaw4k6DviUg

And here's where I originally stored the font: https://www.dafont.com/razer-blackwidow.font

**Comment by joao7yt** [comment]
Yes yes, I meant a system default font...

Here's it: https://mega.nz/#!OclCCQwT!Mk6TWMZmA7d_Aw99pRbJpFVtNUk3_EDcpaw4k6DviUg

And here's where I originally stored the font: https://www.dafont.com/razer-blackwidow.font

**Comment by ThoNohT** [comment]
Thanks!

I think NohBoard might need to restart to actually see the updated list of installed system fonts by the way. So I might just ask the user to restart after installing the font.

**Comment by ThoNohT** [comment]
Thanks!

And I think NohBoard might need to restart to have the updated system font collection by the way. So I might just load it with the default font, and prompt the user to restart after installing the font.

**Comment by joao7yt** [comment]
Isn’t it possible to have a button saying “Restart Nohboard” and it automatically restart?

I’ve read somewhere about Application.Restart();

**Comment by ThoNohT** [comment]
This commit: 505fb182d366aa7640f90a93b0dfe440b8d64bd3 introduces support for linking to fonts.
This commit: 2157f04ce300f660f0f7b47b063784e47e2ebf3f adds your keyboard, and another one with links to custom fonts. 

You'll have to uninstall the Razer Blackwidow font to test that keyboard on your pc. But you could always test it with the other keyboards in wheels.

**Comment by joao7yt** [comment]
Working fine. It seems like it loads the style anyway with a default system font and if you just close the Load Keyboard window it will keep the default font. Liked it...

Something I noticed is that if you first run nohboard, that's, if no keyboard definition is loaded, and open "Load Keyboard", the prompt saying that there's a custom font missing appears with no links listed... I think it's not intentional, right?

**Comment by ThoNohT** [comment]
That'snot right indeed. And I also realized I still need to add the possibility to enter the download URL in edit mode.

**Comment by joao7yt** [comment]
Oh yes, that’s right.

Another thing I noticed is that sometimes the description of some funcitionalities, those that apear when you hover over some button/checkbox, are displayed in just one big line, without line breaks... I think that’s also not intentional

The one I spoted were those new radio buttons added to the Settings window.

**Comment by ThoNohT** [comment]
- c2538070ef7531f73c76b28ab274af5afb864a7f Fixes the download font controls showing on first startup.
- fbc138157b646adf03dbcd7817c965be23d6082c Adds some line breaks in the tooltips in the settings window.
- 67cbe9d7c9c5f08af567d53b8b95aa8fcf6f62d5 Removes the debugging group in settings, as it was not used anyway.

Now all that needs to be done is add the text area to enter the download url.

**Comment by ThoNohT** [comment]
Finally: 7414b90e2b2b4bc2f8f84d0b1b2c3a2a4e317c85 Allows you to set the link text.

After this is tested, we should be good to go for v2.1.2.

**Comment by joao7yt** [comment]
Some quick tests and all seems fine. Think this issue can be closed
