### ISSUE TITLE
Keyboard style resets to default when changing keyboards

### ISSUE THREAD

**Issue by joao7yt** [ThoNohT/NohBoard#25]
When I click on "Load Keyboard" always the "Keyboard Style" is setted to the default one... Like, it's not a major bug, but it's a little annoying hahah

**Comment by ThoNohT** [comment]
Ok let's test this fist.

**Comment by joao7yt** [comment]
I’m not able to test it this weekend, but on Monday I certainly will.

PS: I think some issues could be closed at this point, like #11 #14 #24 #26 #28 #51

**Comment by joao7yt** [comment]
Seems fine

**Comment by purpley8** [comment]
Hi I can't load the new easy-to-see keyboard to the nohboard app and I could use the reboot to fix it, you know that keyboard and mouse style as it is black and it keeps asking me to make it a .kb file and they won't load or save in the file destination. also, upload this "fixing" into a vid so I can try to fix this easier.
