### ISSUE TITLE
What is the file "gotri.exe" ?

### ISSUE THREAD

**Issue by Rokhan** [ThoNohT/NohBoard#27]
Hello, 

I would like to know what is the file "gotri.exe" that is called in the prebuild event.
Where does this utility comes from ? What does it do ?

Regards

**Comment by ThoNohT** [comment]
gotri is a utility I once built to grab version information from the Git repository, and generate files based on a template and this information. I never publicly released it with source code as I never completely finished it.
It is written in Golang. The version I have included here has the basic functionality, I mean to extend it with documentation and properly open source the code, then release it to GitHub eventually.

**Comment by Rokhan** [comment]
Thanks for answer. Seems interesting. Don't hesitate to push it on github even if it's not finished :-)
