### ISSUE TITLE
Nohboard not working with Windowed Fullscreen World of Warcraft

### ISSUE THREAD

**Issue by Lyvondria** [ThoNohT/NohBoard#31]
Hello,

Nohboard is not working when im using Windowed Fullscreen. If i click on desctiop somewhere, like opening a file or folder, then it works. But when I go ingame, its not working

**Comment by Lyvondria** [comment]
Nevermind, fixed it while running it as Administrator.

**Comment by ThoNohT** [comment]
Alright, nice to hear :)
