### ISSUE TITLE
Text position being reset to default when moving boundaries

### ISSUE THREAD

**Issue by joao7yt** [ThoNohT/NohBoard#35]
When I move a key's boundary, the text position is set to, I guess, the default position. My keyboard definition has a custom text postion, so i could witness the bug, see here: https://youtu.be/eGVjjVLu6YY

**Comment by ThoNohT** [comment]
Handling the text position is a delicate thing indeed. I should give this some more thought. You don't want it to never update, but perhaps only when the text position is different from the default.

**Comment by joao7yt** [comment]
I think there should exist an option to check, if checked, the text pos would be always updated relatively to where it was set. This would work like, for example, imagine if you set an image to a key, if you move a boundary, a specific pixel from that image would also move, but the distances' rate from the pixel to the boundaries would always be the same. 

If the option is unchecked, then the txt pos wouldn't be updated at all.

Idk if i made myself clear hahah it's hard to express myself in English...

**Comment by ThoNohT** [comment]
Should be implemented in b6936c5e7177050f454a6a415990cefa59ea6584
