### ISSUE TITLE
[Opinion] "Edit Element/Keyboard Style" should only appears when in the edit-mode.

### ISSUE THREAD

**Issue by joao7yt** [ThoNohT/NohBoard#38]
I think as they are editing tools, would make more sense to have them apear only when "Start Editing" is pressed. And also have them between the same separator as "Stop Editing" and remove the word "Edit" from the buttons.

It would look like this: https://imgur.com/a/hFmHg

**Comment by ThoNohT** [comment]
It is currently separate from that because style editing was possible before there even was an edit mode. I guess I should reconsider whether they should not be moved to be edit mode specific as well. I'll give this some thought.

**Comment by joao7yt** [comment]
I thought exactly that. And i think it would be more clean look after the change

**Comment by ThoNohT** [comment]
Implemented in 12349fc6359519109f81265c8e23c3615464285c

**Comment by joao7yt** [comment]
You implemented but kept the separator and the "Edit" word before the buttons... just to know: you made on purpose or just forgot? I mean, the separator is not a big deal but if you are already IN the edit-mode, the word "Edit" is redundant. And for example you also didn't put "Edit" in the "Element Properties" button...

**Comment by ThoNohT** [comment]
Ah, the "Edit", I didn't even look at that. I guess I can remove that too.

**Comment by ThoNohT** [comment]
Right, I removed the Edit, I do want to keep the separator there. I like a bit of separation between those forms and the actual direct actions.
