### ISSUE TITLE
Right clicking on another key with the righ click menu already opened won't change the selection

### ISSUE THREAD

**Issue by joao7yt** [ThoNohT/NohBoard#40]
So, let's say you miss right clicked on a key and do again a right click on the key you were wanting to hit, it won't work, you currently need to undo the right click with the left click to be able to.

Video: https://youtu.be/aI9jQZ9LNjQ

**Comment by ThoNohT** [comment]
That is intentional. Say you managed to select a key that is partly hidden, and easily misclicked. This way you can still easily access the right click menu for this key. Because you can just right-click anywhere. It may seem counterintuitive, but this way I keep it consistent with selecting another key with left-clicking.

**Comment by joao7yt** [comment]
With that in mind, you should make "Element Properties" and "Element Style" also behave this way, because currently they are working like I thought this should work, they, for example, go unavailable when right cliking an empty space.

**Comment by joao7yt** [comment]
Oh, and watching my video again I realized that I didn't even select the button, I was just right clicking it. I do understand your point to open the menu pointing to a selected element, but I wasn't even selecting it.

**Comment by ThoNohT** [comment]
Hmmm, clicking another key opens the properties for the selected item. Even when you hover over another item. The only thing is that when it is not hovering over a key that it does not show those properties. I guess I can get those menu items to show when something is selected, indeed.

**Comment by joao7yt** [comment]
Ok, so

**Comment by ThoNohT** [comment]
fda487fedda4f0a126da07b2c836543a2f11ec5d This should fix it.

**Comment by joao7yt** [comment]
so, don't you think the right clicking **without** selecting a key should update the menu? just try yourself, go to edit mode and right click things.

**Comment by ThoNohT** [comment]
Ah, opening the properties window selects a button, opening the style window doesn't. I guess that's what you mean? When I have nothing selected the menu seems to do exactly what it should do.

**Comment by joao7yt** [comment]
Oh, that was a bug that I didn't even see hahaha but that is not what I mean, just watch this video, i think i expressed myself better: https://youtu.be/VHWlQhtmiig

**Comment by joao7yt** [comment]
If you wanna keep the way it already is, there's a bug report at the end of the video.

**Comment by ThoNohT** [comment]
Ah, the highlight is wrong when you right click right into the menu a second time. This doesn't mean the menu is wrong though. It actually works for the point where you're clicking. What I need to do is update the highlight.

**Comment by joao7yt** [comment]
are you sure? does it work for where you are right clicking a second time?

**Comment by joao7yt** [comment]
I think for that to work, the hovering highlighting should still work if the menu is opened, because currently if you open the menu, the hovering highlighting feature stops updating

**Comment by ThoNohT** [comment]
I now only update the highlight whenever I open the menu. Previously I did check the key at that location but did not update the highlight. Have you checkked the new build from d8fb035? It should be fixed there.

**Comment by joao7yt** [comment]
Hmmm, i see. But can't the highlight be updated whenever I hover over the elements with the menu opened? Like it's with the menu closed...

**Comment by ThoNohT** [comment]
This is indeed very hard to achieve, as I get no more events about the location of the mouse. Otherwise, this would have happened automatically. And besides that, I feel that it is best to have the key the menu is currently intended for  remain highlighted.

**Comment by joao7yt** [comment]
Oh yeah, right... limitations...

Anyway, i will test the current version

**Comment by joao7yt** [comment]
so, a few bugs related to it, the most important is that now if there's a selected element and you right click on another element, the program will point to where you right cliked instead of pointing to the selected one. 

The right clicking is highlighting even if not in edit-mode.

There's more bugs, it's easier if you see it: https://youtu.be/QMzu7qBNo3c

**Comment by ThoNohT** [comment]
Right, I think I know what causes all of those bugs. Thanks for this super fast testing by the way.

There's three things I need to improve during menu opening:
- Don't set the highlighted definition if there is a selected definition.
- Don't set the highlighted definition when not in editmode.
- Use a proper StartManipulating() call, in stead of setting the definition as highlighted as it is right now.

**Comment by joao7yt** [comment]
Will the third one fix the program thinking I'm selecting the boundary when it should select the entire element? And also fix the program using my previous position instead of the current one? 

I think these 2 bugs are related, right?

**Comment by ThoNohT** [comment]
Yes, they are basically the same bug, which should be fixed by that third point.

**Comment by ThoNohT** [comment]
Ha @joao7yt, I assigned it to you. Could you test it for me?

https://ci.appveyor.com/project/ThoNohT/nohboard/build/1.0.44

**Comment by joao7yt** [comment]
ok, first bug, i cant click in an empty space without it throwing me an error

**Comment by ThoNohT** [comment]
I fixed that. I'll wait a moment before pushing a new version, if any new bug comes up.

**Comment by ThoNohT** [comment]
Fixed (among others) in https://ci.appveyor.com/project/ThoNohT/nohboard/build/1.0.47
