### ISSUE TITLE
I can't start gotri.exe

### ISSUE THREAD

**Issue by sprinter89** [ThoNohT/NohBoard#41]
Hello.  I was run gotri.exe, but only black screen(console) is appear and I can't do anything. Please help.

**Comment by ThoNohT** [comment]
That is normal if you run gotri.exe without any parameters.

Why do you want to run gotri.exe though? It's just a program that's used in the build pipeline.

**Comment by sprinter89** [comment]
I thought gotri.exe was nohboard.exe's different name because there was only one Executable file :)

**Comment by ThoNohT** [comment]
Gotri.exe is not the exe, the exe of NohBoard is not in the source, as that would be the end product, obtained by compiling the source. Get a compiled version of NohBoard from the releases page: https://github.com/ThoNohT/NohBoard/releases.

**Comment by joao7yt** [comment]
You should also like this link that contains compiled beta versions 
https://ci.appveyor.com/project/ThoNohT/nohboard

**Comment by sprinter89** [comment]
thanks!

**Comment by ThoNohT** [comment]
Beta versions are usually unstable. It's best not to send them to everyone, except for those who do explicitly wish to test. Otherwise I'm going to get more and more support questions about things that are not even released yet.

**Comment by joao7yt** [comment]
I'm sorry
https://m.imgur.com/gallery/YOEQUEU
