### ISSUE TITLE
Linux version nohboard

### ISSUE THREAD

**Issue by sprinter89** [ThoNohT/NohBoard#42]
Hello! I love this nohboard program, but I can't use it in linux(It can start but can't trap my keyboard and mouse). So please make nohboard linux version. Thank you.

**Comment by ThoNohT** [comment]
I'm sorry, but this entire program is made towards Windows, using the .NET framework, GDI+, etc. I don't run any linux systems, so this is not likely to happen.

Related to #26 by the way.

**Comment by gabrielbdornas** [comment]
@sprinter89, I have the same problem and found [this repo](https://github.com/Tiyenti/kbdisplay), maybe it could help if you still need this kind of tool.

**Comment by aznlir88** [comment]
> @sprinter89, I have the same problem and found [this repo](https://github.com/Tiyenti/kbdisplay), maybe it could help if you still need this kind of tool.

Thanks! Will it accept NohBoard layouts?
