### ISSUE TITLE
There's no way to change "ChangeOnCaps" bool in keyboard.json 

### ISSUE THREAD

**Issue by joao7yt** [ThoNohT/NohBoard#43]
So, I was making the keyboard definition for that guy who asked for in the forum and realized there's no option in the Element Properties to chamge "ChangeOnCaps", we need to change it in the file.

**Comment by joao7yt** [comment]
So, i'm on my phone (in class hahaha) did you just close it? I'm not watching the stream hahah

**Comment by ThoNohT** [comment]
Yeah, I added the option to change it. Tested it. I don't think this will really cause many problems, as it is really trivial. But if you manage to find a way to break it, be sure to reopen it!

**Comment by joao7yt** [comment]
So, this option is overwriting the "Show all buttons captalized" in the settings... I think that the settings should overwrite this bool, not the other way.

**Comment by ThoNohT** [comment]
Actually this is how it should work. I didn't change anything about how the property works on a key, I merely added a way to modify it via the interface.

ChangeOnCaps = false is pretty much for all special keys, like numbers and characters. Numbers with shift get special characters, like 1 -> !, 2 -> @, e -> # etc. If you toggle caps lock however, you still type the numbers, so I want NohBoard to also show the numbers. And that is exactly how the feature works now. It's not intended to be used on regular keys that actually change when caps lock is on.

**Comment by joao7yt** [comment]
Ok, makes sense. And another thing: "Show all buttons captalized" is wrongly behaving, i understand it as having all buttons as CAPS is on, but instead is makes all buttons as Shift is holded, because even the numbers get changed. Then if i want to have "Show all buttons captalized" on because i think it's cleaner to have the keys in caps and not changing every time you press shift or caps, I have to disable ChangeOnCaps, this way I loose the ability to press shift and change the numbers. idk if you got it, I trying to say that "Show all buttons captalized" should simulate the caps key turned on, not the shift key holded

**Comment by ThoNohT** [comment]
It actually behaves like Caps Lock, and not as Shift. The only way it would also change the numbers, if you set ChangeOnCaps to true for the number keys.

I'm quite sure it works as intended. I made a video to demonstrate it: https://www.youtube.com/watch?v=7fgJEzszvqQ

**Comment by joao7yt** [comment]
Then why do you loose the ability to change the numbers with "Show all button capitalized" selected? I don't see why.

If you select to follow Shift and Caps, and turn on Caps, you won't see the numbers changing, but, with Caps still on, if you press Shift you will be able to see the numbers changing. Why do you loose it selecting "Show all button capitalized"?

To me, to be honest, changing the numbers with caps is kinda useless, since turning on Caps would never change the numbers. It would make more sense you already block numbers in your code, or only allow change on caps for Letter keys, and then change ChangeOnCaps to "ChangeOnShift", then we could block the numbers in all the settings, or be able to let them change in all the settings...

Conclusion: ChangeOnCaps don't make much sense since for every keyboard definition you have to disable ChangeOnCaps to the number keys. Having it blocked hardcoded would make more sense. A ChangeOnShift feature would do it.

**Comment by joao7yt** [comment]
If blocking the keys in the code is hard, you could just add the ChangeOnShift feature and don't block the number keys when "Show all keys captalized", then if I want to show the number keys changing on Shift even wanting all the keys to be all caps, I could. The way it's right now, I can't.

**Comment by ThoNohT** [comment]
First of all: the code makes no distinction between numbers and letters, or any special key for that matter. So there is no way to block changing in code only for them. If you want a key to never change at all, just give the Text and ShiftText the same value.

The way to specify the difference between normal letters and all other special keys is the ChangeOnCaps value. I introduced it specifically for that.

Also, the show all caps or all lower options were made for people who did not want buttons to be switching labels all the time. If I then let it change on Shift again, that would defeat the purpose of the setting. They are meant to show a static keyboard that only highlights on keypresses, but does not change at all.

So with that, your conclusion has one thing right: ChangeOnCaps must be off for all numbers, because that is the exact reason it was introduced.

The only thing I could think of is add the option to react to shift when the All caps or All lower setting are selected. I guess that's what you mean, it's not a per-key thing but a global setting. I just don't see why you would want to use this, why lock the letters in place, but allow the numbers labels to be switched? It is completely contradictory to how the feature works.

**Comment by joao7yt** [comment]
Ok, then the "Show all button capitalized" is more like "Show all capitalized texts", then the ChangeOnCaps is preventing "Show all button capitalized" to take action on that key. It's also preventing Caps on changing that key, but it's not preventing Shift action, right? 

Ok, then let's say I want all the letter keys to look always capitalized, because I think it's weird them to change, but I think it's ok to the numbers to change on Shift. It's currently not possible to do.

A ChangeOnShift global var would allow the user to have more combinations, as the example above. (The ChangeOnShift would still change on Shift that keys with ChangeOnCaps off)

With such feature, I could set true ChangeOnCaps for all the letter keys, false ChangeOnCaps for the numbers and turn on ChangeOnShift to achieve that behavior. Then only the numbers would show its special character on shift.

If you would want to not show its special character, you simply turn off ChangeOnShift global var.

**Comment by joao7yt** [comment]
The name of the check box would be something like "Still change on shift special keys".

And it could be greyed out if "Follow Caps and Shift" is selected...

**Comment by ThoNohT** [comment]
Implemented in https://github.com/ThoNohT/NohBoard/commit/863bd46d3201834b262d243bdd09429dfe5072fd

Test this out in https://ci.appveyor.com/project/ThoNohT/nohboard/build/1.0.53

This hopefully is also the version I am going to release as v1.0.0.

**Comment by joao7yt** [comment]
That's awesome, that option gave us more freedom. Didn't see any bugs until now.

Can you update my styles before pushing a major?

https://mega.nz/#!OJEyRRza!as59WmKnCDd8mwuJ7FEiWqCLvWo5N_MWwXjzy0MjijE

Now there's only one keyboard.json, since it'll be alot easier to the users to delete all the keys they don't need. I didn't include the "outline*" styles since it needs my font to the letters to fit perfectly inside the outlines. So it's lacking 6 styles. (You can see the styles I'm talking about on the forum.)

**Comment by joao7yt** [comment]
Forgot to say that I changed the "FontFamily" of the styles to Tahoma, since it would crash if my font wasn't there... I will wait to give you with the right font and the missing "outline" styles after the custom handle feature...

**Comment by ThoNohT** [comment]
Aye, nice. I already updated your previous keyboards, and changed the font to Tahoma. But I'll grab this one before releasing it.

**Comment by joao7yt** [comment]
Yes, I sent you the updated one because I saw on appveyor that you updated my styles, but that's the newer version... btw that's why i put tahoma, I downloaded it and saw it put that

**Comment by joao7yt** [comment]
Just passing by to say that i think you forgot to close "Edit Mode" project here on github
