### ISSUE TITLE
Doesn't work with OBS-Studio Game Capture source

### ISSUE THREAD

**Issue by djmattyg007** [ThoNohT/NohBoard#46]
Despite the documentation [here](https://obsproject.com/forum/resources/nohboard.44/) stating that it should, I can't seem to get NohBoard to show up when using the Game Capture source. Using the Window Capture source isn't always an option for me because I only have one monitor, which means the game sits on top of NohBoard and OBS-Studio picks that up instead.

Do you have any hints on how to get it working?

**Comment by ThoNohT** [comment]
You are referring to the old NohBoard documentation. The Rewrite no longer supports game capture. If you get the window capture glitch you describe, then that probably means you are still on Windows 7, and have aero turned off. With aero on, window capture will capture the actual window, not what is on top of it. Please refer to OBS support if you need help with that.
