### ISSUE TITLE
Keys not showing up when being pressed

### ISSUE THREAD

**Issue by lbdBG** [ThoNohT/NohBoard#47]
This only happens when I create them, without using the "normal" layout and deleting everything else except those keys

**Comment by ThoNohT** [comment]
You need to assign the keys a keycode. You can look up the keycodes in the existing kb files. I should really create an update that improves the UI for these keys, but that will take a while.

**Comment by lbdBG** [comment]
Couldn't find any kb files but found this: https://gist.github.com/alganet/4879b4455110d6974ce5
Only use the first set of numbers, for example for Z use code 90.
Thanks for the fast reply!
