### ISSUE TITLE
Translation Support 

### ISSUE THREAD

**Issue by L1cardo** [ThoNohT/NohBoard#49]
Can you add some Chinese translation it the NohBoard?   It would be better if it can be translated into any language we want .

Or you can make it support for us to translate the string it the file .

**Comment by L1cardo** [comment]
I could help to do the translating.

**Comment by joao7yt** [comment]
I can also help translating to Brazilian Portuguese.

A folder called “translations” with .txts inside it. The structure could be like this:

“Portuguese”
{
    “Load_Keyboard”
    {
        “translation” “Carregar teclado”
    }
    “Close”
    {
        “translation” “Fechar”
    }
    “Example_Using_Variables”
    {
        “translation” “String: {1}, Int: {2}, Float: {3}”
        “#format” “{1:s},{2:i},{3:f}”
    }
    ...
}

It’s the same structure used in sourcemod, a plugin base for Counter-Strike. It’s very versatile. If a translation needs variables inside it, its position could be easily modified if the language needs. The “s” means the first index there will be a string, the “i” means the second index will be an integer and so on...

Inside the NohBoard, the language selection menu would use the file’s first key as the name showed in the menu, in this case “Portuguese”.

It would allow easy modifications to be made, and would also allow people to easily make and send you the translations.

**Comment by joao7yt** [comment]
I can also help translating to Brazilian Portuguese.

A folder called “translations” with .txts inside it. The structure could be like this:

“Portuguese”
{
	“Load_Keyboard”
	{
		“translation” “Carregar teclado”
	}
	“Close”
	{
		“translation” “Fechar”
	}
	“Example_Using_Variables”
	{
		“translation” “String: {1}, Int: {2}, Float: {3}”
		“#format” “{1:s},{2:i},{3:f}”
	}
	...
}

It’s the same structure used in sourcemod, a plugin base for Counter-Strike. It’s very versatile. If a translation needs variables inside it, its position could be easily modified if the language needs. The “s” means the first index there will be a string, the “i” means the second index will be an integer and so on...

Inside the NohBoard, the language selection menu would use the file’s first key as the name showed in the menu, in this case “Portuguese”.

It would allow easy modifications to be made, and would also allow people to easily make and send you the translations.

**Comment by ThoNohT** [comment]
I'll look into some localization frameworks available for C#. Ideally I'd have the translations done on Crowdin, where I currently also contribute to the obs-studio translations.

**Comment by L1cardo** [comment]
You can have a look to this [Playnite](https://github.com/JosefNemec/Playnite). It really did good in localization. 
Crowdin is a good option too. I did Chinese translations for obs studio on Crowdin, and it is really convenient .  
NohBoard is really a nice software, it is perfect now,and it would be even more nice if it can be localized!

**Comment by joao7yt** [comment]
Hmm, really cool, didn't know about Crowdin.
