### ISSUE TITLE
NohBoard window offscreen and invisible if it was ever previously closed while minimized.

### ISSUE THREAD

**Issue by Dunbaratu** [ThoNohT/NohBoard#50]
(This was on Windows 8, on a two monitor setup where each monitor is running from a different graphics device. (One from the Nvidia card for gaming, one from the motherboard video for everything else.))

My NohBoard (NohBoard-ReWrite-v1.0.1) was invisible when I would run NohBoard.exe.  The window never appeared anywhere and I couldn't see it.  But, the taskbar still showed a miniaturized view of the NohBoard window running, but I could never make the window appear on screen and therefore could not click on it to change any NohBoard settings.

I couldn't figure out why for a long time but eventually I narrowed it down to these steps that will reliably re-create the problem for me every time:

- 1 : Run NohBoard.  Window appears.  (I don't know if this is relevant, but I always run NohBoard on the secondary stream monitoring monitor (situated to the left of the main gaming monitor).)
- 2 : Minimize NohBoard window so it's still running but the window doesn't show.
- 3 : Quit NohBoard.exe from the icon taskbar while it is still minimized.
- 4 : From now on whenever I launch NohBoard.exe, the window refuses to appear.  Note I don't merely mean that it's minimized.  I mean that when I try to de-minimize it and make it appear on screen again, it refuses to do so.  It is now impossible to make the window appear.  It will never appear again until I manually fix it with step 5 below.
- 5: I finally found out that this is happening because the values in ``NohBoard.json`` for ``"X"`` and ``"Y"`` are both being set to the bogus value ``-32000`` by NohBoard whenever I quit NohBoard while it is minimized.  These bogus values are making the window get drawn off-screen out of bounds.  Whatever they previously were, NohBoard clobbers X and Y's values with -32000.  I can get the window to start showing up again by closing NohBoard and manually editing the json file, setting X and Y both to zero.  Then when I re-run NohBoard the window will appear and behave normally.  However if I ever forget again and close NohBoard while it is minimized, the bug happens again and the values are back to -32000.

**Comment by joao7yt** [comment]
Interesting bug. And it's confirmed, also happening here.

**Comment by jackfranzen** [comment]
Had the same issue, editing nohboard.json to (50, 50) worked, it had gotten set to (-32,000, -32,000)
