### ISSUE TITLE
NohBoard window can't be moved normally

### ISSUE THREAD

**Issue by LotBlind** [ThoNohT/NohBoard#52]
It looks like you have to right-click and select "move" to be able to relocate it on the screen. Is this intentional? This is something you have to do each time if you want the window to be on the side of the screen but not minimized for purposes of making sure it's updating for OBS recordings.

**Comment by ThoNohT** [comment]
This should definitely not be the case. I'll mark it as a bug, so I can look at it later and see if I can reproduce it.

**Comment by LotBlind** [comment]
Turns out it's not a bug: it's just that the area that you have to click is really small because of how small the window itself is for the particular layout I'm using (just numpad). I tried dragging by the greyed-out minimize button but that doesn't seem to work for any window.

If anyone wanted to use an even thinner layout, two buttons wide, THEN looks like you can't move by dragging. The only thing I'm thinking you could do about this is if there was an easy way to scale every button up together with the canvas. Although even if I just make the canvas bigger, I get the benefit of easy draggability and I just have to crop the window in OBS... or use a color key to fade it out.

Conclusion and summary, maybe there's no reason to bother with this.

**Comment by ThoNohT** [comment]
Ah, that makes sense. This is just an artifact of the way how Windows handles small windows. I don't think I'll change anything about that. It's always possible to just make the window bigger, and capture just a part of it.
