### ISSUE TITLE
New key doesn't retain changes

### ISSUE THREAD

**Issue by LotBlind** [ThoNohT/NohBoard#55]
EDIT: Okay, cracked it. This happens whenever you click on any key on your virtual keyboard to get it focused, then try to edit its properties. When you're done, it temporarily stores the changes, but reverts back to the old values the moment you click anywhere in the window, and you'll see that key was still selected. Relatedly, you can even drag a key around after selecting it by clicking anywhere on the window. Feel free to ignore the rest of this post if that's enough to help you fix it.

-----

I tried making various changes to a new manually added key. All the changes seemed to be reverted the first time I clicked on the canvas. In fact it seems to be reacting to mouse1 even though it doesn't have any keys assigned to it ostensibly. (This happens by default so I'm guessing it's a feature)

Can't reproduce it but I captured it on video at least in case that's any use. Ignore the window on the left, that's where I wanted to copy values from.

https://drive.google.com/file/d/1A0VZa1kOfPnKfBHDF4vx5LHy-0SJyxAt/view?usp=sharing

Will post again if I figure out how I did it. Note that towards the end of the video, I accidentally noticed I couldn't move a given boundary down, just up. It seems to be unrelated, so I'll just open a different Issue for that...

EDIT: Well, the next key I added behaved fine, stored all the changes as expected. The next one after that had this bug again... I don't know what I did differently but it looks to be very random.

Wait, it doesn't just react to clicking mouse1, it literally stays selected the whole time, no matter which part of the window I'm clicking. I can even drag it around by clicking anywhere.

Looks like the problem arises if you first drag the key around.

**Comment by joao7yt** [comment]
Confirmed, if an element is highlighted and edited, if left clicking on the nohboard canvas, the key is reset.

**Comment by ThoNohT** [comment]
Please test this.
