### ISSUE TITLE
Can't use alt in nohboard?

### ISSUE THREAD

**Issue by jackfranzen** [ThoNohT/NohBoard#57]
I can't get alt to map through nohboard, the best guess I've got is "18" for the key-code, but no response. Is there a work-around or do I have the wrong key-code?

P.s. Love the software, always recommending it. I'll submit my KILLER skin once this is fixed 👍

**Comment by jackfranzen** [comment]
redownloaded to get the default skins, 164 is alt

**Comment by ThoNohT** [comment]
Nice 😃

**Comment by jackfranzen** [comment]
off topic, but where do I submit this skin and style?

**Comment by ThoNohT** [comment]
A new github issue would be as good a place as any. I'll include it in the next release.

Bear in mind though that I am currently in the process of buying/moving to a new house. Together with my already limited free time this means that until around May, I won't really have any time to work on NohBoard at all. But after all that's done, there's a few bugs waiting for me at least, so I'll probably make a release with it in it around that time.
