### ISSUE TITLE
Overlay stop working when i unfocus the window

### ISSUE THREAD

**Issue by TyssanFR** [ThoNohT/NohBoard#60]
The program not working when im on a game (fullscreen ot not , same problem) only work when i im on my desktop or the window of the program. 

Need to be focus on NohBoard to work.

(sorry bad english lul)

Thanks.

**Comment by Leayal** [comment]
Try to run the NohBoard as Admin and not minimize it to taskbar.
See if it's working.

**Comment by ThoNohT** [comment]
This has been an eternal gripe. Sometimes it works, sometimes it doesn't. The hints @Leayal  gave are the correct ones.

- Running as admin gives NohBoard a higher chance of receiving the keycodes before a game catches them and doesn't send them on.
- Minimizing might stop the window from rendering.

Still, in some situations, NohBoard will just stop refreshing, and I have no idea why it does this. At this point I don't feel like there are any other things that can be done about them. Unless specific situations can be provided I won't spend more effort on this. So I'll close this now.
