### ISSUE TITLE
Scroll Lock / Caps Lock / Num lock state indicators

### ISSUE THREAD

**Issue by Rabbadack** [ThoNohT/NohBoard#61]
Hello,
i´m new to this board but already made my first layouts with Nohboard.
It´s really easy to use and i like it very much.
But:
There is one thing i could not manage.
I want led´s on the board that indicate when cl, num and roll is pressed.
What i did is to copy the corresponding keys and giving them another look.
The trouble is that the led´s only light as long as the key is pressed.
Is there any way to keep the light on until the corresponding key is hit again ?
![grafik](https://user-images.githubusercontent.com/41386963/42896119-3ee1dc0e-8abc-11e8-82ac-8cc82036caa2.png)

**Comment by ThoNohT** [comment]
Not at the moment. This should not be too hard to implement though. They would probably be extra keycodes. I'll mark this as a feature request.

**Comment by ThoNohT** [comment]
Added in bcc0e9a02debf0ecc17e9e37c8aa6d103f0f8124

Please test this: https://ci.appveyor.com/project/ThoNohT/nohboard/build/artifacts Note that I added a us_intl_statekeys keyboard to the Normal group that has all of the lock keys in the top right.

**Comment by ThoNohT** [comment]
Also note that the documentation should be updated once this is published, that these keys now  exist.

For now special keys are:
Enter: 1025
Caps lock state: 1026
Num lock state: 1027
Scroll lock state: 1028

**Comment by joao7yt** [comment]
Working.
