### ISSUE TITLE
Cycling through elements doesn't work.

### ISSUE THREAD

**Issue by joao7yt** [ThoNohT/NohBoard#71]
Seems like it's not working at all... I'm in 1.2.0

**Comment by joao7yt** [comment]
The weird thing is that that change where clicking outside any element deselects any selection is happening, but clycling just won't

**Comment by ThoNohT** [comment]
Alright, I'll try to look at that soon.

**Comment by ThoNohT** [comment]
I can't reproduce the issue. It seems to work fine. I've tried stacking different types of buttons on top of each other, and the selection flawlessly switches between them. Could you make an example video perhaps, maybe I can see what's going on from that.

**Comment by joao7yt** [comment]
I recorded it, seems like it just doesn't work with certain keys... must be something which my keyboard. Anyway, the program allowed me to open the keyboard, even the problem is with it... I think it should detect there's something wrong with the keyboard.

https://www.youtube.com/watch?v=L95yaY1dqoI

**Comment by joao7yt** [comment]
joao7yt’s keyboard

**Comment by ThoNohT** [comment]
Could you test this for me?

**Comment by joao7yt** [comment]
Working properly.
