### ISSUE TITLE
New icon art

### ISSUE THREAD

**Issue by joao7yt** [ThoNohT/NohBoard#76]
I decided to spend some time on it because i thought I could give NohBoard a more professional look by changing its icon.

What are your opinion about this? You can also propose changes to it too...

![icon256](https://user-images.githubusercontent.com/10665193/46044635-ba4c1600-c0f1-11e8-80b1-391569f7acfb.png)256
![icon72](https://user-images.githubusercontent.com/10665193/46044634-ba4c1600-c0f1-11e8-8a6c-e8b23169aeb1.png)72
![icon60](https://user-images.githubusercontent.com/10665193/46044632-ba4c1600-c0f1-11e8-8f04-6b2321b84eef.png)60
![icon48](https://user-images.githubusercontent.com/10665193/46044631-b9b37f80-c0f1-11e8-8ad5-61a754022017.png)48
![icon40](https://user-images.githubusercontent.com/10665193/46044629-b9b37f80-c0f1-11e8-8ed7-ab52a2617145.png)40
![icon32](https://user-images.githubusercontent.com/10665193/46044628-b9b37f80-c0f1-11e8-9d3f-24a4bfee2212.png)32
![icon24](https://user-images.githubusercontent.com/10665193/46044627-b9b37f80-c0f1-11e8-928d-8b57e5128b02.png)24
![icon20](https://user-images.githubusercontent.com/10665193/46044626-b91ae900-c0f1-11e8-8014-a3dcbb1f2fc9.png)20
![icon16](https://user-images.githubusercontent.com/10665193/46044623-b91ae900-c0f1-11e8-9d75-a4e672f21972.png)16

**Comment by ThoNohT** [comment]
I like the idea of the buttons, and the green theme is still in there. I'm certainly considering changing to this logo. The one I currently have is just hand-drawn using ms paint or something. But I have a few remarks:

1. I feel like the text is a bit too small. The current logo can be read properly at this scale, but this text is very hard to read when it's in my taskbar.
See this image for an example: ![afbeelding](https://user-images.githubusercontent.com/3800650/46572891-b9d33b00-c98d-11e8-9598-e638595afce8.png)
2. The logo usues a rather small part of the screen, having the top right and bottom left empty. Maybe that needs to be filled with a green gradient, or perhaps the buttons can be a lot bigger and overlap slightly, so they also fill a bit more of that empty space.

**Comment by joao7yt** [comment]
I see that the icon used in your screenshot is the 256 rescaled... I don’t think it’s using the 16 version. 

You need to use gimp to make a .ico containing all the png versions

**Comment by joao7yt** [comment]
Here is the .ico containing all the versions
[Icon.zip](https://github.com/ThoNohT/NohBoard/files/2457655/Icon.zip)

**Comment by joao7yt** [comment]
If you still find the text small, then I can make changes to it, but try with the "compiled" .ico to see if it's better...

**Comment by ThoNohT** [comment]
I'll try that soon, thanks.

**Comment by ThoNohT** [comment]
![afbeelding](https://user-images.githubusercontent.com/3800650/51063298-a4a82100-15fa-11e9-961d-a4c7259377fa.png)

I still feel like the letters are just slightly too small to read on my screen. (27" 1440p)

**Comment by joao7yt** [comment]
See if I got it right this time [Icon.zip](https://github.com/ThoNohT/NohBoard/files/2751587/Icon.zip)

I modified the 16 and 20 versions.

**Comment by ThoNohT** [comment]
I like this: ed5e02c4ab3a955768a7b5263034a0e8b4034692

It'll be in the next release
