### ISSUE TITLE
Add support for Xbox 360 contolers

### ISSUE THREAD

**Issue by Dan9er** [ThoNohT/NohBoard#77]
I have a Rock Band Strato that I'm using to play Clone Hero, and I would like to have a controller display on my videos. However, all the solutions out there only support the standard Xbox 360 controller with no layout customization options. Can support for Xbox 360 input be added to NohBoard? I'll even offer to make some default layouts.

**Comment by joao7yt** [comment]
I think it's a duplicate of #22

**Comment by Dan9er** [comment]
Duplicate of #22
