### ISSUE TITLE
New "Detect" feature preventing me to type in other programs

### ISSUE THREAD

**Issue by joao7yt** [ThoNohT/NohBoard#79]
When closing the Keyboard Key Properties window when the "Detecting..." is activated, the program seems to doesn't terminate the detecting process right, so I can't use my keyboard in other programs.

**Comment by Butt4cak3** [comment]
Confirming this issue. I was pretty sure I tested closing the window while the detection is active, but apparently I did not.

**Comment by ThoNohT** [comment]
Good catch. I could fix that either by preventing the window closing while detection is active, or by stopping detection when closing the window.

I think the second option would be the best one,
