### ISSUE TITLE
New Quake Keyboard Layout

### ISSUE THREAD

**Issue by flyingmongoose** [ThoNohT/NohBoard#84]
So I took some time building out a template for Quake Champions, though it can definitely be modified to work with any Quake edition (the only thing that makes it "Quake" really is the mouse and a similar font to what is used in Champions as the default type font for notices [but not the same].)

[Download link for Quake Template](https://tunedchaos.tech/nohboard-quake-template/)

Don't know if you want to include any more templates but Gimp XCF files are included in the zip.

#101

**Comment by ThoNohT** [comment]
The next release will have support for downloading custom fonts, or at least linking to them. I feel it would be better to make a version of this keyboard that uses the standard way of showing the letters and numbers, and provide a link to the font download.

If that's done, I'll definitely include these keyboards in the package.

**Comment by flyingmongoose** [comment]
Thanks for the update @ThoNohT I don't have time to get this update done **right now** maybe in the next couple of weeks I'll do so.

I will leave this open for now so I can make sure it stays on my list of things to do.

Maybe a valentines day update for you guys.

**Comment by flyingmongoose** [comment]
I've resubmitted my pull with proper updates.

So..... happy easter I guess?

**Comment by ThoNohT** [comment]
This was merged in the other PR, closing.
