### ISSUE TITLE
Stops Working Upon Keypress

### ISSUE THREAD

**Issue by Perpetucake** [ThoNohT/NohBoard#87]
The software will capture movement, as soon as a key/mouse button is pressed- the entire software stops working until reopening. It will display the pressed key held down, then it stops working completely.

Ran as admin, restarted, tried old versions.

No errors thrown, no crash, just halts completely.

**Comment by Butt4cak3** [comment]
So, just to clarify, the program basically doesn't work for you because it freezes as soon as you press one button?

This is gonna be hell to reproduce.

**Comment by Perpetucake** [comment]
It will display the first button, show it as held down for a second (even if immediately released), then it will be blank forever. It also completely breaks mouse movement, which works beforehand until the first keypress. The entire rest of the UI still works, editing, settings, etc. No crash, no error, just an immediate halt of the key capture routine.

Tried multiple keyboards, unplugged all other devices, used a new user account, tried all compatibility modes.

**Comment by Perpetucake** [comment]
Ok, so it works 100% when in the Win10 "Apps," but nowhere else. (I only have the bare requirement apps, Settings and Edge) As soon as any other window is brought into focus it fails.

**Comment by Perpetucake** [comment]
Alright so I was able to solve the issue. [Synergy](https://symless.com/synergy) server service running in elevated mode as causes this behavior. Feel free to close the issue, nevermind!
