### ISSUE TITLE
Network support

### ISSUE THREAD

**Issue by designgears** [ThoNohT/NohBoard#90]
The only thing I'd really like to see is an api so you can run one instance on your gaming pc and the other on a streaming pc that receives data over the network about key presses and mouse input.

**Comment by ThoNohT** [comment]
For now, the trap keyboard/mouse feature has been made to support this scenario. If you clone your keyboard and mouse input to the gaming and streaming pc, then you can enable the trap keyboard/mouse feature, and have the stuff being recorded on the streaming pc, without it actually performing those actions and messing with your streaming software, or whatever else is going on on that pc.

The feature itself is pretty big, not something I will have time to work on on short term sadly.
