### ISSUE TITLE
Is there a way to add a checkbox that enables/disables the render of keypress if minimized ?

### ISSUE THREAD

**Issue by Teltboy** [ThoNohT/NohBoard#91]

**Comment by ThoNohT** [comment]
Why would you want to disable rendering?

**Comment by joao7yt** [comment]
I think what he really wants is to enable it, because currently it’s not possible to have the keys rendered if minimized...

**Comment by ThoNohT** [comment]
Yeah. I haven't really done anything to disable that, that just happens to be how those windows forms work. A checkbox isn't going to be able to change that sadly.

**Comment by Teltboy** [comment]
Yeah because right now if you want to stream, it's impossible to do it with only one screen if you want to integrate it into OBS. But I'm experienced in C#, I could help you to generate a picture of the keyboard each time a key is pressed, so you could integrate it into the stream as a picture

**Comment by ThoNohT** [comment]
You can simply leave it open behind the game if you have only one screen though

**Comment by Teltboy** [comment]
doesn't work but thanks for the link
