### ISSUE TITLE
ABNT2 and "/" Key

### ISSUE THREAD

**Issue by rsigim** [ThoNohT/NohBoard#93]
Hello! I was trying to make a ABNT2 keyboard but I cant make the / working.

In accordance to [this site](http://www.mhavila.com.br/link/unix/abnt2/) the key code is 89, yet pressing ever key nothing lights up, its need to be coded or Im doing something wrong? Thanks

**Comment by ThoNohT** [comment]
The changes to detect a keycode are already done, I just haven't published it yet for some reason. I just found out. In the meantime, it would be keycode 191.
