### ISSUE TITLE
Errors related to gotri.exe when trying to build

### ISSUE THREAD

**Issue by joao7yt** [ThoNohT/NohBoard#94]
So, I was trying to build Nohboard to try somethings out but got 2 erros related to gotri... How could I fix those?

![untitled](https://user-images.githubusercontent.com/10665193/51194148-9cd5ce80-18d1-11e9-8393-257eeca99888.png)

**Comment by ThoNohT** [comment]
It looks like it can't find some file, that's what code 2 should be. The best way to debug is, is to copy & paste the command it's trying to execute into a console window, and see what output it gives. If you can give me that, I might be able to tell more.

**Comment by joao7yt** [comment]
panic: Unable to find git executable. Are you sure it is installed and in the path?

goroutine 1 [running]:
panic(0x5272c0, 0xc0820089d0)
        C:/Go/src/runtime/panic.go:481 +0x3f4
thonoht.com/gotri/revisionInfo.execute(0x589820, 0x3, 0xc082031cc0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
        d:/Projects/Go/src/thonoht.com/gotri/revisionInfo/revisionInfo.go:95 +0x310
thonoht.com/gotri/revisionInfo.GetRevisionInfo(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        d:/Projects/Go/src/thonoht.com/gotri/revisionInfo/revisionInfo.go:34 +0x15e
main.main()
        d:/Projects/Go/src/thonoht.com/gotri/gotri.go:38 +0x74a

What does it mean? I have no idea what panic is... sorry, I'm still a noob hahha

**Comment by ThoNohT** [comment]
It's just golang's version of an error. It says it can't find git, have you
installed git?

**Comment by joao7yt** [comment]
ok, that was it... i just watched what git is. I'm just new to programming. now i can run the program in visual studio
