### ISSUE TITLE
Change name window

### ISSUE THREAD

**Issue by RobinSchapendonkGames** [ThoNohT/NohBoard#97]
is there a way that i can change the name from NohBoard v1.2.1 to just NohBoard?

**Comment by joao7yt** [comment]
You need to edit the project and recompile it... but why tho?

**Comment by ThoNohT** [comment]
I could add a setting for it of course. The one reason I heard of is when you want to window capture two different NohBoard instances. OBS won't do that if they have the same title, IIRC.

**Comment by joao7yt** [comment]
Working.
