### ISSUE TITLE
[Feature Request]Translucent inactive UI Elements

### ISSUE THREAD

**Issue by ilovuxay** [ThoNohT/NohBoard#98]
Imagining that you're giving a live-streaming show of MMORPG games, and then the keyboard UI （pinned to the foreground）clearly would block some area of the full screen.
So, it could be better the NorBoard allow users to hide almost all of the UI elements, except the active keys that are pressed at the moment.
Even, the display mode of the active keys can be wireframe instead of filled entity!

**Comment by joao7yt** [comment]
I don’t get it... the nohboard window shouldn’t be shown at all... you are supposed to capture it using window capture in obs studio and color key the background color... why would you want to show the “behind the scenes” of how nohboard looks like when not capturing it?

**Comment by ilovuxay** [comment]
![QQ截图20190406093935](https://user-images.githubusercontent.com/17734954/55663391-f655f580-584f-11e9-8ae0-773559d020aa.png)

I mean, when I capture the screen, the nohboard windows covers large area of the game window. So if only you can make the background color (blue) and inactive squares (dark grey) simply hidden!

**Comment by joao7yt** [comment]
To make the noh background transparent you need to add a chroma key filter provided by your streaming software in the window capture that you are capturing the nohboard window. 

Then to make unpressed keys to vanish you need to make a custom keyboard definition; just right click on the nohboard screen, go to Edit Mode, then right click again and go to Keyboard Style, there you choose the color of the background and the text of unpressed keys. Make them the same color as the chroma key color you are using.

**Comment by ilovuxay** [comment]
Aha ... Thank you for your advice .... however here in China the popular streaming software (such as douyu ) don't seem to provide such a chroma key filter feature ... They just capture the game window, nohboard window and then overlay one with the other ... 

And even more .. the steam community (the website) is now completely blocked in China, haha. It is very difficult to climb over the Great Fire Wall.

**Comment by joao7yt** [comment]
download obs studio, I think you will like it... if you can't access it, I can reupload the installer somewhere you can access and then you download it

**Comment by flyingmongoose** [comment]
The other possibity, if OBS Studio isn't available to just download, you may be able to compile it yourself, as it is open source.

**Comment by ThoNohT** [comment]
While a good idea, I tried this before. And this doesn't really work. As I'm using a simple windows form, and drawing on top of it. Even not drawing would leave the background gray. There's translucency things, but those really mess up the rendering and capturing probably. The best way to go is indeed to use a capture software that can do color key.
